### ISSUE TITLE
The default branch was renamed to `main`

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-spreadsheet-editor#53]
It looks like the default branch is currently `master`.

Maybe it could be renamed to `main` for consistency with the other repos in the `jupyterlab-contrib` org?

**Comment by krassowski** [comment]
Done!

> The default branch has been renamed!
> master is now named main
> 
> If you have a local clone, you can update it by running the following commands.
> 
> ```
> git branch -m master main
> git fetch origin
> git branch -u origin/main main
> git remote set-head origin -a
> ```

**Comment by jtpio** [comment]
Thanks!

Closing as completed. We can keep the issue pinned for now if needed.
