### ISSUE TITLE
Support for JupyterLab 4.0

### ISSUE THREAD

**Issue by nataquinones** [jupyterlab-contrib/jupyterlab-spreadsheet-editor#61]
Hello,
This is a great extension, but the current version (0.6.1) does not work with >JupyterLab 4.0. Would be awesome to support it. Thanks!

**Comment by krassowski** [comment]
Version [`v0.7.1`](https://github.com/jupyterlab-contrib/jupyterlab-spreadsheet-editor/releases/tag/v0.7.1) supporting JupyterLab 4+ is now available on PyPI and should be on conda-forge soon:
- https://pypi.org/project/jupyterlab-spreadsheet-editor/0.7.1/
- https://anaconda.org/conda-forge/jupyterlab-spreadsheet-editor
