### ISSUE TITLE
Support for Jupyterlite

### ISSUE THREAD

**Issue by vfreysz** [jupyterlab-contrib/jupyterlab-spreadsheet-editor#62]
This is an awesome feature for jupyterlab.

When i try to install it in jupyterlite 0.2.3 (https://jupyterlite.readthedocs.io) i have the following error.

```PYTHON
ValueError: Can't find a pure Python 3 wheel for 'tornado>=6.1.0'.
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
You can use `await micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.
```

Not sure why, since tornado is used by jupyterlab server.

**Comment by krassowski** [comment]
I think this would be solved with https://github.com/jupyterlab-contrib/jupyterlab-spreadsheet-editor/issues/61. I will add a comment here you once the lab 4.0 upgrade is ready for testing

**Comment by krassowski** [comment]
Can you test with `jupyterlab-spreadsheet-editor` [v0.7.1](https://github.com/jupyterlab-contrib/jupyterlab-spreadsheet-editor/releases/tag/v0.7.1)?

**Comment by vfreysz** [comment]
I can't get it to work.
When I try on my server or on https://jupyter.org/try-jupyter/lab/

`import micropip
await micropip.install("jupyterlab-spreadsheet-editor")
`

there is no more warning but it seems that nothing happened...

**Comment by martinRenou** [comment]
Ah unfortunately you won't be able to install this extension that way. You need to make your own deployment of Jupyterlite and follow [this guide](https://jupyterlite.readthedocs.io/en/stable/howto/configure/simple_extensions.html) for installing external extensions.

**Comment by vfreysz** [comment]
Thanks, I had forgotten that.

Works perfectly now.

My docker composes if anyone wants to test.

```PYTHON
version: "3.7"
services: 
  jupyterlite:
    image: continuumio/miniconda3
    command: bash -c "
      pip install jupyterlite-core==0.2.3 && \
      pip install jupyter_server && \
      pip install jupyterlite-pyodide-kernel && \
      pip install jupyterlite-core[all] && \
      pip install ipywidgets==8.1.1 &&\
      pip install jupyterlab-spreadsheet-editor &&\
      pip install bqplot &&\
      pip install plotly &&\

      jupyter lite build &&\
      jupyter lite serve --port=8087"
    ports: 
      - 8087:8087
    container_name: jupyterlite
```

**Comment by krassowski** [comment]
> Works perfectly now.

:tada: Thanks for confirming - I will close this issue now.
