### ISSUE TITLE
Incompatible with Python 3.12?

### ISSUE THREAD

**Issue by AmranA14** [jupyterlab-contrib/jupyterlab-spreadsheet-editor#63]
## Description

In Windows 10, when using Python 3.12, the CLI outputs "Failed building wheel for pyzmq" when installing via pip install in a mamba environment. With **3.11** and below, the extension **worked** in Jupyterlab.

![image](https://github.com/jupyterlab-contrib/jupyterlab-spreadsheet-editor/assets/159123201/6cf57b92-8b1b-408f-a1a0-12f0e38f9f1a)

## Reproduce

1. Install rustup and mambaforge
2. create new mamba environment in miniforge3 prompt with specified 'python=3.12' in 

Used yaml file for environment:

```
name: test
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyter
  - jupytext
  - jupyterlab
  - lxml
  - requests
  - numba
  - pip
  - cython
  - matplotlib
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - h5py
  - pytables
  - pyarrow
  - pytest
  - pytest-cov
  - sphinx
  - sphinx_rtd_theme
  - pyyaml
  - yaml
  - setuptools
  - nodejs
  - ipysheet

  - pip:
    - juliacall
    - rise
    - kaleido
    - jupyterlab_rise
```

3. activate environment and run pip install jupyterlab-spreadsheet-editor

**Comment by krassowski** [comment]
This is not related to this extension - it does not use pyzmq. What oyu might have experience could have been a downgrade to older JupyterLab version when installing the `jupyterlab-spreadsheet-editor` as JupyterLab 4.0+ support is only now being added.
